title: Pratiman Homepage
author: Pratiman Patel
email: pratiman_patel@hotmail.com
description: >-
  This is Pratiman webpage with some blogs.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pratiman-91.github.io" # your site's origin, e.g. https://forestry.io
name:         Pratiman Blogs

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
plugins:
  - jekyll-feed
  - jekyll-menus

emptyArray: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
