title: Pratiman Homepage
author: Pratiman Patel
email: pratiman_patel@hotmail.com
description: >-
  This is my webpage with some blogs.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
  -
    scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: pratiman
      commenting: open
plugins:
  - jekyll-feed
  - jekyll-menus

emptyArray: []

comments:
  receiver: https://pratiman-91.github.io//api/PostComment}}
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
